# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/508_source_soft_exp/zvbi-test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/508_source_soft_exp/zvbi-test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/508_source_soft_exp/zvbi-test/CMakeFiles /home/pi/508_source_soft_exp/zvbi-test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/508_source_soft_exp/zvbi-test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named anc-dump

# Build rule for target.
anc-dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anc-dump
.PHONY : anc-dump

# fast build rule for target.
anc-dump/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anc-dump.dir/build.make CMakeFiles/anc-dump.dir/build
.PHONY : anc-dump/fast

#=============================================================================
# Target rules for targets named zvbi-test

# Build rule for target.
zvbi-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zvbi-test
.PHONY : zvbi-test

# fast build rule for target.
zvbi-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zvbi-test.dir/build.make CMakeFiles/zvbi-test.dir/build
.PHONY : zvbi-test/fast

anc-dump.o: anc-dump.c.o

.PHONY : anc-dump.o

# target to build an object file
anc-dump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anc-dump.dir/build.make CMakeFiles/anc-dump.dir/anc-dump.c.o
.PHONY : anc-dump.c.o

anc-dump.i: anc-dump.c.i

.PHONY : anc-dump.i

# target to preprocess a source file
anc-dump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anc-dump.dir/build.make CMakeFiles/anc-dump.dir/anc-dump.c.i
.PHONY : anc-dump.c.i

anc-dump.s: anc-dump.c.s

.PHONY : anc-dump.s

# target to generate assembly for a file
anc-dump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anc-dump.dir/build.make CMakeFiles/anc-dump.dir/anc-dump.c.s
.PHONY : anc-dump.c.s

zvbi-test.o: zvbi-test.c.o

.PHONY : zvbi-test.o

# target to build an object file
zvbi-test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zvbi-test.dir/build.make CMakeFiles/zvbi-test.dir/zvbi-test.c.o
.PHONY : zvbi-test.c.o

zvbi-test.i: zvbi-test.c.i

.PHONY : zvbi-test.i

# target to preprocess a source file
zvbi-test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zvbi-test.dir/build.make CMakeFiles/zvbi-test.dir/zvbi-test.c.i
.PHONY : zvbi-test.c.i

zvbi-test.s: zvbi-test.c.s

.PHONY : zvbi-test.s

# target to generate assembly for a file
zvbi-test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zvbi-test.dir/build.make CMakeFiles/zvbi-test.dir/zvbi-test.c.s
.PHONY : zvbi-test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... anc-dump"
	@echo "... zvbi-test"
	@echo "... anc-dump.o"
	@echo "... anc-dump.i"
	@echo "... anc-dump.s"
	@echo "... zvbi-test.o"
	@echo "... zvbi-test.i"
	@echo "... zvbi-test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

